[keys.search.results]
trigger_replacement = "A-r"

[editor_open]
command = "nvim --server $NVIM --remote-send '<cmd>lua EditLineFromScooter(\"%file\", %line)<CR>'"

[preview]
syntax_highlighting_theme = "base16-ocean.dark"
